// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEd403dHLdBmo4iO-STi38Dk-xBY5W0fk',
    appId: '1:769614237008:android:9b19f62ca81da7d011b055',
    messagingSenderId: '769614237008',
    projectId: 'mosalla-3f0e6',
    storageBucket: 'mosalla-3f0e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVhlcuAfBg7Z-PDT2_cDw4vwSpinK86E8',
    appId: '1:769614237008:ios:85991cd52d27f3fc11b055',
    messagingSenderId: '769614237008',
    projectId: 'mosalla-3f0e6',
    storageBucket: 'mosalla-3f0e6.firebasestorage.app',
    iosBundleId: 'x.sohaibahmed.mosalla',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQ1LvHfRDxTojikaNkUCFrCk4cZ7ZLVw',
    appId: '1:769614237008:web:19545d9ba9ecc1d811b055',
    messagingSenderId: '769614237008',
    projectId: 'mosalla-3f0e6',
    authDomain: 'mosalla-3f0e6.firebaseapp.com',
    storageBucket: 'mosalla-3f0e6.firebasestorage.app',
    measurementId: 'G-3TLE75LZGH',
  );
}